[MODEL][ERR] Replaced var I with internal_curr
farms_network/morris_lecar.c:1963:10: error: expected member name or ';' after declaration specifiers
  double I;
  ~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/complex.h:42:11: note: expanded from macro 'I'
          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/complex.h:40:21: note: expanded from macro '_Complex_I'

Variable I seems to be an indentifier in the current xcode complex number. This causes
a compilation error